### PR TITLE
Add basic command line interface

### LINKED ISSUE #2: Basic CLI UI
A program, or 3:
- Receive all messages waiting, display them, log them
- Continuously check for new messages and receive+display+log them as they arrive
- Transmit a single message (and maybe receive a waiting message if necessary).

No async or CLI needed, keep it simple.

### PR DESCRIPTION
**Pull request by HarkonenBade**
Fixes #2, #7, #9

### CODE REVIEW

**Comment by adamgreig** [comment]
Looks good. Do messages received during send_recv actually get printed? Looks like they might only get written to the log file? Perhaps in general it would be easiest to just have logging go to file and console together, then logging can handle opening, writing and syncing files.

**Comment by HarkonenBade** [comment]
When messages get sent or received the RockBlock class calls self._log_msg() to save the messages to the log file. I inserted a logging.info print out into that function so that for the CLI UI I just set the logging level to info and that will then print out the messages as they are received/sent.

**Comment by cillian64** [comment]
Issues:

Default env variables if not otherwise set.  Logfile in ~/rockblock.log and default serial device /dev/ttyACM0

**Comment by cillian64** [comment]
Actually serial devices will be ttyUSBx instead of ttyACMx.  The primary user will probably be adam's laptop where the satmodem is always ttyUSB3 (ttyUSB0-2 are occupied on adam's laptop by GPS and GSM modem).  ttyUSB3 is a bit of a derpy default though, so I wouldn't blame you for choosing ttyUSB0 and adam setting an env variable (my laptop for instance would be ttyUSB0), but the workflow!

**Comment by adamgreig** [comment]
Just tried rockblock.py recv and got:

```
ERROR:root:Expected response 0, got  instead
Traceback (most recent call last):
  File "rockblock.py", line 337, in <module>
    main()
  File "rockblock.py", line 328, in main
    rb = RockBlock(os.environ["RBUI_PORT"], os.environ["RBUI_LOG"])
  File "rockblock.py", line 126, in __init__
    self._setup_device()
  File "rockblock.py", line 112, in _setup_device
    self._expect_response(RSP_OK)
  File "rockblock.py", line 83, in _expect_response
    raise Exception()  # TODO: Proper exceptions
Exception
```

**Comment by adamgreig** [comment]
```
DEBUG:root:Issuing command AT\r
DEBUG:root:Received response 
DEBUG:root:Issuing command ATV0\r
DEBUG:root:Received response OK
ERROR:root:Expected response 0, got OK instead
Traceback (most recent call last):
  File "rockblock.py", line 337, in <module>
    main()
  File "rockblock.py", line 328, in main
    rb = RockBlock(os.environ["RBUI_PORT"], os.environ["RBUI_LOG"])
  File "rockblock.py", line 126, in __init__
    self._setup_device()
  File "rockblock.py", line 112, in _setup_device
    self._expect_response(RSP_OK)
  File "rockblock.py", line 83, in _expect_response
    raise Exception()  # TODO: Proper exceptions
Exception
```

**Comment by adamgreig** [comment]
```
DEBUG:root:Issuing command AT\r
DEBUG:root:Received response 0
DEBUG:root:Issuing command AT+SBDMTA=0\r
DEBUG:root:Received response 0
DEBUG:root:Issuing command AT+SBDSX\r
DEBUG:root:Received response +SBDSX: 0, 83, 0, -1, 1, 0
DEBUG:root:Received response 0
DEBUG:root:Issuing command AT-MSSTM\r
DEBUG:root:Received response -MSSTM: 1c5529aa
DEBUG:root:Received response 0
DEBUG:root:Issuing command AT+CSQF\r
DEBUG:root:Received response +CSQF:5
DEBUG:root:Received response 0
DEBUG:root:Issuing command AT+SBDIXA\r
DEBUG:root:Received response 
DEBUG:root:Received response 
DEBUG:root:Received response +SBDIX: 2, 83, 1, 13, 13, 5
DEBUG:root:Received response 0
DEBUG:root:Issuing command AT+SBDRT\r
DEBUG:root:Received response +SBDRT:
DEBUG:root:Received response I am a rocket0
INFO:root:<--- I am a rocket
Traceback (most recent call last):
  File "rockblock.py", line 337, in <module>
    main()
  File "rockblock.py", line 332, in main
    recv_loop(rb)
  File "rockblock.py", line 297, in recv_loop
    rb.recv_all()
  File "rockblock.py", line 261, in recv_all
    recv.append(self._read_msg_from_buffer(sesh_status.mt_len))
  File "rockblock.py", line 237, in _read_msg_from_buffer
    self._log_msg("<--- " + msg)
  File "rockblock.py", line 49, in _log_msg
    log_msg = "{ts} {data}\n".format(ts=utc_timestamp(),
  File "rockblock.py", line 31, in utc_timestamp
    return datetime.utcnow().isoformat()
AttributeError: 'module' object has no attribute 'utcnow'
```

**Comment by adamgreig** [comment]
Also the log file doesn't appear to be getting written to at all, I set the env var and the file gets created but is empty.

**Comment by adamgreig** [comment]
It would be nice if it checked for any messages in the rockblock buffer at startup and printed them out, in case of errors during reading that leave a message in the rockblock buffer but not printed to the screen. Otherwise they'll get overwritten without being printed and we miss them.

**Comment by adamgreig** [comment]
Oh, it does write to the log file, but only writes received messages, not any other information (such as what's displayed when you --debug on the CLI). I think it would be best if it could write the full debug-level information out to the log file.

**Comment by adamgreig** [comment]
```
ERROR:root:Timed out due to insufficient signal strength
```

Maybe just keep on going? I imagine leaving recv running for hours as signals come and go so we can occasionally check for new messages, so not much point in timing out.

**Comment by adamgreig** [comment]
It would be great if it could also log like "Checking to see if any messages are queued", "Downloading queued messages" etc before the relevant operations to make it clearer what's going on.

**Comment by cillian64** [comment]
Perhaps two separate logfiles, debug.log (everything adam said) and messages.log (just the messages)?

**Comment by adamgreig** [comment]
:+1:

**Comment by adamgreig** [comment]
This seems to happen when plugged in for the first time

```
DEBUG:root:Issuing command AT\r
DEBUG:root:Received response 
DEBUG:root:Issuing command ATV0\r
DEBUG:root:Received response 
ERROR:root:Expected response 0, got  instead
```

**Comment by adamgreig** [comment]
Oh ignore - that happens only while the module is still powering up I think.

**Comment by cillian64** [comment]
Maybe don't ignore and handle gracefully and meaningfully if possible

**Comment by adamgreig** [comment]
But then I do get this a few times before it starts working:

```
DEBUG:root:Issuing command AT\r
DEBUG:root:Received response 
DEBUG:root:Issuing command ATV0\r
DEBUG:root:Received response OK
ERROR:root:Expected response 0, got OK instead
```

**Comment by adamgreig** [comment]
When we run this:

```
DEBUG:root:Received response +SBDSX: 0, 18, 0, -1, 0, 0
```

It would be really nice if the numbers could be decoded and printed out, e.g. "no messages waiting, message id bla, etc"

**Comment by HarkonenBade** [comment]
Comments noted. I'll whack something together later tonight. The last one is slightly awkward, as that debug message is the generic print of any line read from the modem. So to special case for interpreting status lines would involve scanning every line read and trying to decide what it is. I hadn't anticipated the debugging mode being run for general use.

**Comment by adamgreig** [comment]
I assume you already parse a bit of the status line anyway to work out when to download new messages? To be honest if it could just print the syntax for that line on startup I can work it out myself :p

**Comment by adamgreig** [comment]
Also it feels like the delays between commands are a lot longer than necessary but not sure how you determine that.

**Comment by HarkonenBade** [comment]
I'll poke a look at that, not sure if the way i'm accessing the port is causing more waits until timeouts or something. Also the bit about the status is because that debug print statement is immediately after I do a read from the port in the _read_response() function. I can add another debug print in the two places that parse a status line to also print the parsed statuses.

**Pull request merged**
